global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: A
        port: 9100

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.56.101:8080', '192.168.56.102:8080']
