global:
  scrape_interval: 15s  # Tần suất thu thập metric (tinh chỉnh nếu cần)

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

remote_write:
  - url: "http://influxdb:8086/api/v2/write"
    basic_auth:
      username: "admin"
      password: "password"